[build]
  publish = "frontend"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  # Direktori ini harus ada di root folder fungsi (netlify/functions/).
  # 'included_files' memberitahu bundler Netlify untuk menyertakan file-file ini
  # di dalam bundle fungsi. Path di sini RELATIF terhadap root proyek.
  included_files = ["netlify/functions/template_spt.docx"]
  node_bundler = "esbuild" # Pastikan bundler menggunakan esbuild