[build]
  publish = "frontend"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  included_files = ["netlify/functions/template_spt.docx"]
  node_bundler = "esbuild"