[build]
  # Direktori ini memberitahu Netlify di mana file-file situs (HTML, CSS, JavaScript) Anda berada.
  publish = "frontend"
  # Direktori ini memberitahu Netlify di mana mencari Netlify Functions Anda.
  functions = "netlify/functions"

# Bagian ini mengkonfigurasi pengalihan (redirects).
# Ini penting agar permintaan dari front-end Anda (misalnya ke /api/generate-document)
# dapat diarahkan dengan benar ke Netlify Function Anda.
[[redirects]]
  from = "/api/*" # Setiap permintaan yang datang ke jalur ini di situs Anda
  to = "/.netlify/functions/:splat" # Akan diarahkan ke Netlify Function yang sesuai
  status = 200 # Kode status 200 menunjukkan pengalihan berhasil

# Bagian ini mengkonfigurasi Netlify Functions.
[functions]
  # Kita tidak lagi perlu menyertakan file template secara eksplisit di sini,
  # karena kita sudah menyematkannya langsung ke dalam kode JavaScript fungsi.
  # Namun, kita tetap menentukan bundler yang digunakan.
  node_bundler = "esbuild" # Menggunakan 'esbuild' adalah default modern yang direkomendasikan untuk bundling fungsi Node.js